employee_management/urls.py
from django.contrib import admin
from django.urls import path
from app_1.views import depart, pretty, user, admin, account, order, chart, upload, city
from app_1.views import task
from django.urls import path, re_path
from django.views.static import serve
from django.conf import  settings

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    # path("admin/", admin.site.urls),
    # 部门管理
    path("depart/list/", depart.depart_list),
    path("depart/add/", depart.depart_add),
    path("depart/delete/", depart.depart_delete),
    path("depart/<int:nid>/edit/", depart.depart_edit),
    path("depart/multi/", depart.depart_multi),
    # 用户管理
    path("user/list/", user.user_list),
    path("user/add/", user.user_add),
    path("user/model/form/add/", user.user_model_form_add),
    path("user/<int:nid>/edit/", user.user_edit),
    path("user/<int:nid>/delete/", user.user_delete),
    # 靓号管理
    path("pretty/list/", pretty.pretty_list),
    path("pretty/add/", pretty.pretty_add),
    path("pretty/<int:nid>/edit/", pretty.pretty_edit),
    path("pretty/<int:nid>/delete/", pretty.pretty_delete),
    # 管理员管理
    path("admin/list/", admin.admin_list),
    path("admin/add/", admin.admin_add),
    path("admin/<int:nid>/edit/", admin.admin_edit),
    path("admin/<int:nid>/delete/", admin.admin_delete),
    path("admin/<int:nid>/reset/", admin.admin_reset),
    # 登录
    path("login/", account.login),
    # 注销
    path("logout/", account.logout),
    path("image/code/", account.image_code),
    # 任务管理
    path("task/list/", task.task_list),
    path("task/ajax/", task.task_ajax),
    path("task/add/", task.task_add),
    # 订单管理
    path("order/list/", order.order_list),
    path("order/add/", order.order_add),
    path("order/delete/", order.order_delete),
    path("order/detail/", order.order_detail),
    path("order/edit/", order.order_edit),
    path("chart/list/", chart.chart_list),

    path("chart/bar/", chart.chart_bar),
    path("chart/pie/", chart.chart_pie),
    path("chart/highcharts/", chart.high_charts),

    path("upload/list/", upload.upload_list),
    path("upload/form/", upload.upload_form),
    path("upload/model/form/", upload.upload_model_form),

    path("city/list/", city.city_list),
    path("city/add/", city.city_add),
]

app_1/models.py
from django.db import models


# Create your models here.


class Admin(models.Model):
    """ 管理员 """
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    def __str__(self):
        return self.username


class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name='标题', max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
    # create_time = models.DateTimeField(verbose_name="入职时间")
    create_time = models.DateField(verbose_name="入职时间")
    # 无约束
    # depart_id = models.BigIntegerField(verbose_name="部门ID")

    # 1.有约束
    # -to, 与那张表相关联
    # -to_field,表中的那一列关联
    # 2.部门表被删除
    # 2.1级联删除
    depart = models.ForeignKey(verbose_name="部门", to="Department", to_field="id", on_delete=models.CASCADE)
    # 2.2 置空
    # depart = models.ForeignKey(to="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL)
    # 3.在Django中作约束
    # 第一个元素表示存在数据库内真实的值，第二个表示页面上显示的具体内容。在浏览器页面上将显示第二个元素的值。
    gender_choices = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)


class PrettyNum(models.Model):
    """ 靓号表 """
    mobile = models.CharField(verbose_name="手机号", max_length=11)
    price = models.IntegerField(verbose_name="价格", default=0)
    level_choices = (
        (1, "1级"),
        (2, "2级"),
        (3, "3级"),
        (4, "4级"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    status_choices = (
        (1, "已占用"),
        (2, "未使用")
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)


class Task(models.Model):
    """ 任务 """
    level_choices = (
        (1, "紧急"),
        (2, "重要"),
        (3, "临时"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    title = models.CharField(verbose_name="标题", max_length=64)
    detail = models.TextField(verbose_name="详细信息")
    user = models.ForeignKey(verbose_name="负责人", to="Admin", on_delete=models.CASCADE)


class Order(models.Model):
    """ 订单 """
    oid = models.CharField(verbose_name="订单号", max_length=64)
    title = models.CharField(verbose_name="名称", max_length=32)
    price = models.IntegerField(verbose_name="价格")

    status_choices = (
        (1, "待支付"),
        (2, "已支付"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)
    admin = models.ForeignKey(verbose_name="管理员", to="Admin", on_delete=models.CASCADE)


class Boss(models.Model):
    """ 老板 """
    name = models.CharField(verbose_name="姓名", max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    img = models.CharField(verbose_name="头像", max_length=128)


class City(models.Model):
    """ 城市 """
    name = models.CharField(verbose_name="名称", max_length=32)
    count = models.IntegerField(verbose_name="人口")
    # 本质上数据库也是CharField,自动保存数据
    img = models.FileField(verbose_name="LOGO", max_length=128, upload_to='city/')

app_1/views/account.py
from django.shortcuts import redirect, render, HttpResponse
from django import forms
from app_1.utils import bootstrap
from app_1 import models
from app_1.utils.encrypt import md5
from app_1.utils.code import check_code
from io import BytesIO


class LoginForm(bootstrap.BootStrapForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput,
        required=True
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(render_value=True),
        required=True
    )
    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True
    )

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)


# class LoginModelForm(forms.ModelForm):
#     class Meta:
#         model = models.Admin
#         fields = ["username", "password"]


def login(request):
    """ 登录 """
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {'form': form})
    form = LoginForm(data=request.POST)
    # print(form.changed_data)
    if form.is_valid():
        # 验证码的校验
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', "")
        if code.upper() != user_input_code.upper():
            form.add_error("code", "验证码错误")
            return render(request, 'login.html', {'form': form})

        # 去数据库校验用户名和密码是否正确，获取用户对象，None
        # admin_object = models.Admin,objects.filter(username=xxx, password=xxx).first()
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password", "用户名或密码错误")
            return render(request, 'login.html', {'form': form})
        # 用户名和密码正确
        # 网站生成随机字符串；写到用户浏览器的cookie中；再写入到session中
        request.session["info"] = {'id': admin_object.id, 'name': admin_object.username}
        # sessipn可以保存7天
        request.session.set_expiry(60 * 60 * 24 * 7)

        return redirect("/admin/list/")
    return render(request, 'login.html', {"form": form})


def logout(request):
    request.session.clear()
    return redirect("/login/")


def image_code(request):
    """ 生成验证码 """
    img, code_string = check_code()
    # 写入到自己的session中（以便后续获取验证码在进行校验）
    request.session['image_code'] = code_string
    # 给session设置60s超时
    request.session.set_expiry(60)

    # print(code_string)
    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())

app_1/views/admin.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError
from app_1 import models
from app_1.utils import pagination

from django import forms
from app_1.utils.bootstrap import BootStrapModelForm
from app_1.utils.encrypt import md5
from django.http import HttpResponse


def admin_list(request):
    """ 管理员列表 """
    # info_dict = request.session["info"]
    # 构造搜索
    data_dict = {}
    search_data = request.GET.get('q', "")
    if search_data:
        data_dict["username__contains"] = search_data
    queryset = models.Admin.objects.filter(**data_dict)
    page_object = pagination.Pagination(request, queryset)
    context = {
        "queryset": page_object.page_queryset,
        "page_string": page_object.html(),
        "search_data": search_data
    }
    return render(request, 'admin_list.html', context)


class AdminModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput(render_value=True)
    )

    class Meta:
        model = models.Admin
        fields = ["username", "password"]
        widgets = {
            "password": forms.PasswordInput(render_value=True)
        }

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)

    def clean_confirm_password(self):
        pwd = self.cleaned_data.get("password")
        confirm = md5(self.cleaned_data.get("confirm_password"))
        if confirm != pwd:
            raise ValidationError("密码不一致")
        # 此返回什么，以后保存什么到数据库
        return confirm


def admin_add(request):
    """ 添加管理员 """
    title = "新建管理员"
    if request.method == "GET":
        form = AdminModelForm()
        return render(request, 'change_add.html', {"form": form, "title": title})
    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')

    return render(request, 'change_add.html', {'form': form, "title": title})


class AdminEditModelForm(BootStrapModelForm):
    class Meta:
        model = models.Admin
        fields = ['username']


class AdminResetModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput(render_value=True)
    )

    class Meta:
        model = models.Admin
        fields = ['password', 'confirm_password']
        widgets = {
            "password": forms.PasswordInput(render_value=True)
        }

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        md5_pwd = md5(pwd)
        exits = models.Admin.objects.filter(id=self.instance.pk, password=md5_pwd).exists()
        if exits:
            raise ValidationError("不能和以前的密码一致")
        return md5_pwd

    def clean_confirm_password(self):
        pwd = self.cleaned_data.get("password")
        confirm = md5(self.cleaned_data.get("confirm_password"))
        if confirm != pwd:
            raise ValidationError("密码不一致")
        # 此返回什么，以后保存什么到数据库
        return confirm


def admin_edit(request, nid):
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        # return render(request, 'error.html', {"msg": "数据不存在"})
        return redirect("/admin/list/")
    title = "编辑管理员"
    if request.method == "GET":
        form = AdminEditModelForm(instance=row_object)
        return render(request, 'change_add.html', {"form": form, "title": title})
    form = AdminEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change_add.html', {"form": form, "title": title})


def admin_delete(request, nid):
    models.Admin.objects.filter(id=nid).delete()
    return redirect("/admin/list/")


def admin_reset(request, nid):
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return redirect("/admin/list/")
    title = "重置密码 - {}".format(row_object.username)
    if request.method == "GET":
        form = AdminResetModelForm()
        return render(request, 'change_add.html', {"form": form, "title": title})
    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect("/admin/list/")
    return render(request, 'change_add.html', {"form": form, "title": title})

app_1/views/chart.py
from django.shortcuts import render, redirect
from django.http import JsonResponse


def chart_list(request):
    return render(request, "chart_list.html")


def chart_bar(request):
    """ 构造柱状图的数据 """
    legend = ['kkk', 'hhh']
    series_list = [
        {
            "name": 'kkk',
            "type": 'bar',
            "data": [15, 28, 36, 10, 100]
        },
        {
            "name": 'hhh',
            "type": 'bar',
            "data": [15, 28, 36, 10, 100]
        },
    ]
    x_axis = ['1月', '2月', '3月', '4月', '5月']
    result = {
        "status": True,
        "data": {
            'legend': legend,
            'series_list': series_list,
            'x_axis': x_axis,
        }
    }
    return JsonResponse(result)


def chart_pie(request):
    db_data_list = [
        {"value": 1111, "name": "IT部门"},
        {"value": 888, "name":"运营"},
        {"value": 999, "name":"新媒体"}
    ]
    result = {
        "status": True,
        "data": db_data_list,
    }
    return JsonResponse(result)


def high_charts(request):
    return render(request, "chart_high_charts.html")

app_1/views/city.py
from django.shortcuts import render
from app_1 import models

from django import forms
from app_1.utils.bootstrap import BootStrapForm
from app_1.utils.bootstrap import BootStrapModelForm
import os
from django.conf import settings
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from app_1 import models


def city_list(request):
    queryset = models.City.objects.all()
    return render(request, 'city_list.html', {"queryset": queryset})


class UpModelForm(BootStrapModelForm):
    class Meta:
        model = models.City
        fields = "__all__"


def city_add(request):
    title = "新建城市"
    if request.method == "GET":
        form = UpModelForm()
        return render(request, 'upload_form.html', {"form": form, 'title': title})

    form = UpModelForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        # 字段 + 路径 写入数据库中
        form.save()
        return redirect("/city/list/")
    return render(request, 'upload_form.html', {"form": form, 'title': title})

app_1/views/depart.py
from django.shortcuts import render, redirect
from app_1 import models
from django.http import HttpResponse

""" 部门 """


def depart_list(request):
    """部门列表"""
    queryset = models.Department.objects.all()
    return render(request, 'depart_list.html', {'queryset': queryset})


def depart_add(request):
    """添加部门"""
    if request.method == "GET":
        return render(request, 'depart_add.html')
    title = request.POST.get("title")
    models.Department.objects.create(title=title)
    return redirect("/depart/list/")


def depart_delete(request):
    """删除部门"""
    nid = request.GET.get('nid')
    models.Department.objects.filter(id=nid).delete()
    return redirect("/depart/list/")


def depart_edit(request, nid):
    """修改部门"""
    if request.method == "GET":
        row_object = models.Department.objects.filter(id=nid).first()
        print(row_object.id, row_object.title)
        return render(request, 'depart_edit.html', {"row_object": row_object})
    title = request.POST.get("title")
    models.Department.objects.filter(id=nid).update(title=title)
    return redirect("/depart/list/")



from openpyxl import load_workbook


def depart_multi(request):
    """ 批量上传 """
    # 1.获取用户上传的文件对象
    file_object = request.FILES.get("exc")
    # print(type(file_object))

    # 2.对象传递给openpyxl,由openpyxl读取文件的内容
    wb = load_workbook(file_object)
    sheet = wb.worksheets[0]

    # cell = sheet.cell(1, 1)
    # print(cell.value)
    # 3.循环获取每一行数据
    for row in sheet.iter_rows(min_row=2):
        text = row[0].value
        exists = models.Department.objects.create(title=text).exists()
        if not exists:
            models.Department.objects.create(title=text)
    return HttpResponse('上传文件')

app_1/templates/admin_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app_1/templates/city_list.html
{% extends 'layout.html' %}
{% block content %}
    <div>
        <div class="container">
            <div style="margin-bottom: 10px">
                <a class="btn btn-success" href="/city/add/">
                    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                    新建城市
                </a>
            </div>
            <div class="panel panel-default">
              <!-- Default panel contents -->

                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    城市列表
                </div>

                  <!-- Table -->
                <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Logo</th>
                        <th>名称</th>
                        <th>人口</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for obj in  queryset%}
                      <tr>
                        <th>{{ obj.id }}</th>
                        <td>
                            <img src="/media/{{ obj.img }}" style="height: 80px">
                        </td>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.count }}</td>
                      </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
        </div>
    </div>
{% endblock %}

app_1/templates/error.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <h3></h3>
        <div class="alert alert-danger" role="alert">{{ msg }}</div>
    </div>
{% endblock %}

app_1/templates/pretty_list.html
{% extends 'layout.html' %}
{% block content %}
    <div>
        <div class="container">
            <div style="margin-bottom: 10px" class="clearfix">
                <a class="btn btn-success" target="_blank" href="/pretty/add/">
                    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                    新建靓号
                </a>
                <div style="float: right; width: 300px">
                    <form method="get">
                         <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Search for..." value="{{ search_data }}"/>
                             <span class="input-group-btn">
                                 <button class="btn btn-default" type="submit">
                                     <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                 </button>
                             </span>
                         </div><!-- /input-group -->
                    </form>
                </div>
            </div>
            <div class="panel panel-default">
              <!-- Default panel contents -->
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    靓号列表
                </div>
                  <!-- Table -->
                <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>号码</th>
                        <th>价格</th>
                        <th>等级</th>
                        <th>状态</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for obj in queryset %}
                      <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.mobile }}</td>
                        <td>{{ obj.price}}</td>
                        <td>{{ obj.get_level_display}}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/pretty/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/pretty/{{ obj.id }}/delete/">删除</a>
                        </td>
                      </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
            <div class="clearfix">
                <ul class="pagination">
                    {{ page_string }}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

app_1/templates/task_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">表单</div>
            <div class="panel-body">
                <form id="formAdd">
                    <div class="clearfix">
                        {% for field in form %}
                            <div class="col-xs-6">
                                <div class="form-group" style="position: relative; margin-bottom: 20px">
                                    <label>{{ field.label }}</label>
                                    {{ field }}
                                    <span class="error-msg" style="color: red; position: absolute;"></span>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-xs-12">
                            <button id="btnAdd" type="button" class="btn btn-primary">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="panel panel-default">
              <!-- Default panel contents -->
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    任务列表
                </div>
                  <!-- Table -->
                <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>标题</th>
                        <th>级别</th>
                        <th>负责人</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for obj in queryset %}
                      <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.title }}</td>
                        <td>{{ obj.get_level_display }}</td>
                        <td>{{ obj.user.username }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/admin/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/admin/{{ obj.id }}/delete/">删除</a>
                        </td>
                      </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
        <ul class="pagination">
            {{ page_string }}
        </ul>
        <div style="height: 1000px"></div>
        <div>
            <h1>任务管理</h1>
            <p>示例1</p>
            <input id="btn1" type="button" class="btn btn-primary" value="点击"/>
            <h3>示例2</h3>
            <input type="text" id="txtUser" placeholder="姓名"/>
            <input type="text" id="txtAge" placeholder="年龄"/>
            <input id="btn2" type="button" class="btn btn-primary" value="点击"/>
            <h3>示例3</h3>
            <form id="form3">
                <input type="text" name="user" placeholder="姓名"/>
                <input type="text" name="age" placeholder="年龄"/>
                <input type="text" name="email" placeholder="邮箱"/>
                <input type="text" name="more" placeholder="介绍"/>
            </form>
            <input id="btn3" type="button" class="btn btn-primary" value="点击3"/>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(function () {
            // 页面框架加载完成后代码自动执行
            bindBtn1Event();
            bindBtn2Event();
            bindBtn3Event();
            bindBtnAddEvent();
        })
        function bindBtn1Event() {
            $("#btn1").click(function () {
                $.ajax({
                      url: '/task/ajax/',
                      type: "post",
                      data: {
                        n1: 123,
                        n2: 456,
                        n3: 789
                    },
                    dataType: "json",
                    success: function(res){
                          console.log(res);
                          console.log(res.status);
                          console.log(res.data);
                    },
                })
            })
        }
        function bindBtn2Event() {
            $("#btn2").click(function () {
                $.ajax({
                      url: '/task/ajax/',
                      type: "post",
                      data: {
                        name: $("#txtUser").val(),
                        age: $("#txtAge").val(),
                    },
                    dataType: "JSON",
                    success: function(res){
                          console.log(res);
                          console.log(res.status);
                          console.log(res.data);
                    },
                })
            })
        }
        function bindBtn3Event() {
            $("#btn3").click(function () {
                $.ajax({
                    url: '/task/ajax/',
                    type: "post",
                    {#  data: {#}
                    {#    name: $("#txtUser").val(),#}
                    {#    age: $("#txtAge").val(),#}
                    {#,#}
                    data:$("#form3").serialize(),
                    dataType: "JSON",
                    success: function(res){
                          console.log(res);
                          console.log(res.status);
                          console.log(res.data);
                    },
                })
            })
        }
        function bindBtnAddEvent() {
            $("#btnAdd").click(function () {
                $(".error-msg").empty();
                $.ajax({
                    url: '/task/add/',
                    type: "post",
                    {#  data: {#}
                    {#    name: $("#txtUser").val(),#}
                    {#    age: $("#txtAge").val(),#}
                    {#,#}
                    data:$("#formAdd").serialize(),
                    dataType: "JSON",
                    success: function(res){
                        if(res.status){
                            alert("添加成功");
                            location.reload();
                        } else {
                            console.log(res.error);
                            $.each(res.error, function (name, data) {
                                console.log(name, data);
                                $("#id_" + name).next().text(data[0]);
                            })
                        }
                    },
                })
            })
        }

    </script>
{#    <script type="text/javascript">#}
{#        function clickMe() {#}
{#            $.ajax({#}
{#                url: '/task/ajax/',#}
{#                type: "post",#}
{#                data: {#}
{#                    n1: 123,#}
{#                    n2: 456,#}
{#                    n3: 789#}
{#                },#}
{#                success: function (res) {#}
{#                    console.log(res);#}
{#                }#}
{#            })#}
{#        }#}
{#    </script>#}
{% endblock %}

app_1/templates/user_list.html
{% extends 'layout.html' %}
{% block content %}
    <div>
        <div class="container">
            <div style="margin-bottom: 10px">
                <a class="btn btn-success" target="_blank" href="/user/add/">
                    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                    新建用户
                </a>
                <a class="btn btn-success" target="_blank" href="/user/model/form/add/">
                    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                    新建用户MODELFORM
                </a>
            </div>
            <div class="panel panel-default">
              <!-- Default panel contents -->

                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    用户列表
                </div>

                  <!-- Table -->
                <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>姓名</th>
                        <th>密码</th>
                        <th>年龄</th>
                        <th>账户余额</th>
                        <th>入职时间</th>
                        <th>性别</th>
                        <th>所属部门</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for obj in queryset %}
                      <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.password }}</td>
                        <td>{{ obj.age }}</td>
                        <td>{{ obj.account }}</td>
                        <td>{{ obj.create_time | date:"Y-m-d"}}</td>
                        <td>{{ obj.get_gender_display }}</td>
                        <td>{{ obj.depart.title }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete/">删除</a>
                        </td>
                      </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
{% endblock %}